# ------------ DONNEES D'INITIALISATION -----------------------------------------------
TITRE_FENETRE = "Pokémon Emeraude Python v0.01"
SCREEN_SCALE = 3
SCREEN_WIDTH = 240 * SCREEN_SCALE
SCREEN_HEIGHT = 160 * SCREEN_SCALE
BEGIN_SCREEN_GAME = 3
TEST_MODE = True

# ------------ DOSSIERS ---------------------------------------------------------------
MAIN_DIRECTORY = "F:/Python/Pokemon Emeraude"

# ASSETS
ASSETS_DIRECTORY = MAIN_DIRECTORY + "/assets"
# -
ASSETS_MAIN_MENU = ASSETS_DIRECTORY + "/main_menu"
ASSETS_LOADING_MENU = ASSETS_DIRECTORY +"/loading_menu"
ASSETS_NEW_GAME = ASSETS_DIRECTORY +"/new_game"
ASSETS_DIALBOX = ASSETS_DIRECTORY + "/dialogues"
ASSETS_POKEMONS = ASSETS_DIRECTORY + "/pokemons"
ASSETS_TILESETS = ASSETS_DIRECTORY + "/tilesets"
ASSETS_CHARACTERS = ASSETS_DIRECTORY + "/characters"

# FONTS
FONTS_DIRECTORY = MAIN_DIRECTORY + "/font"

# LINES
LINES_DIRECTORY = MAIN_DIRECTORY + "/lines"

# JSON
JSON_DIRECTORY = MAIN_DIRECTORY + "/json"

# MAPS
MAPS_DIRECTORY = MAIN_DIRECTORY + "/maps"
# ------------ FICHIERS ---------------------------------------------------------------

# JSON
JSON_POKEMON_BASIC_DATA = JSON_DIRECTORY + "/pokedex.json"

# FONTS
FONT_MAIN_DIALOGBOX = FONTS_DIRECTORY + "/pokemon-emerald.ttf"
FONT_MAIN_DIALOGBOX_SIZE = 14

# DIALOG
PROF_SEKO_INTRO_1 = LINES_DIRECTORY + "/prof_seko_intro.txt"
TEST_PROF_SEKO_INTRO_1 = LINES_DIRECTORY + "/test_prof_seko_intro.txt"

# MISC
IMG_DIALOGBOX = ASSETS_DIALBOX + "/dialogbox.png"
IMG_CURSOR_NEXT =  ASSETS_DIALBOX + "/img_defilement_dialog.png"

# MAIN
LOGO_FENETRE = ASSETS_MAIN_MENU + "/icon.png"
LOGO_POKEMON_EMERAUDE = ASSETS_MAIN_MENU + "/logo_pokemon_emeraude.png"
IMG_BACKGROUND_MAIN_MENU_1 = ASSETS_MAIN_MENU + "/rayquaza_1.png"
IMG_BACKGROUND_MAIN_MENU_2 = ASSETS_MAIN_MENU + "/rayquaza_2.png"
IMG_POKEMON_TITLE = ASSETS_MAIN_MENU + "/logo_pokemon_emeraude.png"
IMG_CREDITS = ASSETS_MAIN_MENU + "/credit.png"
IMG_PRESS_START = ASSETS_MAIN_MENU + "/press_start.png"
IMG_BRUME = ASSETS_MAIN_MENU + "/brume.png"

# LOADING MENU
IMG_BACKGROUND_LOADING_SCREEN = ASSETS_LOADING_MENU + "/background.png"
IMG_NOUVELLE_PARTIE = ASSETS_LOADING_MENU + "/nouvelle_partie.png"
IMG_OPTIONS = ASSETS_LOADING_MENU + "/options.png"
IMG_NOUVELLE_PARTIE_INACTIVE = ASSETS_LOADING_MENU + "/nouvelle_partie2.png"
IMG_OPTIONS_INACTIVE = ASSETS_LOADING_MENU + "/options2.png"

# NEW GAME
IMG_BACKGROUND_NEW_GAME = ASSETS_NEW_GAME + "/background.png"
IMG_UP_GRADIANT_NEW_GAME = ASSETS_NEW_GAME + "/up_gradiant.png"
IMG_PROF_GROUND_NEW_GAME = ASSETS_NEW_GAME + "/prof_ground.png"
IMG_PROF_SEKO_NEW_GAME = ASSETS_NEW_GAME + "/prof_seko.png"
IMG_PROF_ALEX_KITCHEN = ASSETS_NEW_GAME + "/gralex_kitchen_reduced.png"
IMG_POKEBALL_CLASSIC = ASSETS_NEW_GAME + "/pokeball.png"
IMG_POKEBALL_CLASSIC_OPEN = ASSETS_NEW_GAME + "/pokeball_open.png"
IMG_POKEBALL_CLASSIC_FULL_OPEN = ASSETS_NEW_GAME + "/pokeball_full_open.png"
IMG_FLASH_POKEBALL = ASSETS_NEW_GAME + "/flash_"
IMG_CHOIX_GARCON_FILLE = ASSETS_NEW_GAME + "/fenetre_choix_sexe.png"
IMG_FLECHE_CHOIX = ASSETS_NEW_GAME + "/fleche_choix.png"
IMG_PLAYER_MALE = ASSETS_NEW_GAME + "/garcon.png"
IMG_PLAYER_FEMALE = ASSETS_NEW_GAME + "/fille.png"
IMG_CLAVIER_OVERLAY = ASSETS_NEW_GAME + "/clavier_overlay.png"
IMG_CLAVIER_MAJUSCULE = ASSETS_NEW_GAME + "/clavier_majuscule.png"
IMG_CLAVIER_MINUSCULES = ASSETS_NEW_GAME + "/clavier_minuscules.png"
IMG_NEW_GAME_SELECT_PLAYER_NAME = ASSETS_NEW_GAME + "/new_game_select_player_name.png"
IMG_CLAVIER_SIDE_BUTTONS = ASSETS_NEW_GAME + "/clavier_side_buttons.png"
IMG_LETTER_SELECTION_RED = ASSETS_NEW_GAME + "/letter_selection_red.png"
IMG_LETTER_SELECTION_WHITE = ASSETS_NEW_GAME + "/letter_selection_white.png"
IMG_NAME_CURSOR = ASSETS_NEW_GAME + "/name_cursor.png"
IMG_SELECTOR_WIDE = ASSETS_NEW_GAME + "/selector_wide.png"

# POKEMONS
def GET_FRONT_POKEMON(number):
    return ASSETS_POKEMONS + "/"+ str(number) + ".gif"

# ------------ LISTE DES EVENEMENTS --------------------------------------------------
EVENT_OPENNENUPIOT = "OPENNENUPIOT"
EVENT_CHOOSE_SEX = "CHOOSESEX"
EVENT_SHOW_SEX_CHOICE = "SHOWSEXCHOISE"
EVENT_WRITE_PLAYER_NAME = "WRITEPLAYERNAME"
EVENT_SHOW_PROF_AND_NENUPIOT = "SHOWPROFANDNENUPIOT"
EVENT_SHOW_DRESSEUR = "SHOWDRESSEUR"
# ------------ FIN LISTE DES EVENEMENTS ----------------------------------------------

# TILESETS
TILESET_OUTDOORS = ASSETS_TILESETS + "/outdoors.png"
TILESET_INDOORS = ASSETS_TILESETS + "/indoors.png"

# MAPS
MAP_DE_CALIBRAGE = MAPS_DIRECTORY + "/map_de_calibrage.map"
MAP_ROUTE_101 = MAPS_DIRECTORY + "/route_101.map"
MAP_BOURG_EN_VOL = MAPS_DIRECTORY + "/bourg_en_vol.map"

# CHARACTERS
ANIMATION_BUNDLE_PLAYER_MALE = ASSETS_CHARACTERS + "/player_male.png"